### ISSUE TITLE
[serverless-contracts] add support for `{ statusCode, body }` as handler output

### ISSUE THREAD

**Issue by Yoctoboy** [swarmion/swarmion#253]
Hey again,

## Context

I have a lambda function directly integrated to an ApiGateway, meaning I can curl this gateway and it should execute the lambda and return its return value to me.

## Issue

According to the [Lambda Proxy Integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html) doc, it is possible to simply return an object like 
```
{
  statusCode: 401,
  headers: {
    "x-custom-header" : "my custom header value"
  },
  body: JSON.stringify(responseBody)
};
```
in the lambda function and have a `curl` call to the ApiGateway return that same error code (401 in this example).

However, my lambda also uses swarmion's ApiGatewayContract with `getHttpLambdaHandler`. As can be seen in [this function's code](https://github.com/swarmion/swarmion/blob/881fa8a36fc0c6883606da229bea0f4a308e553d/packages/serverless-contracts/src/contracts/apiGateway/features/httpLambdaHandler.ts#L40), if the handler does not crash, the `getHttpLambdaHandler` calls `handlerResponseToLambdaResult` which automatically returns a 200.

I did not know that at first and it can lead to some funny curl output like these 
![Screenshot from 2022-09-05 18-07-00](https://user-images.githubusercontent.com/16920060/188486875-58e3a5eb-a340-4bc3-aaa3-ca2a3f23bdaa.png)
(notice the `HTTP/2 200` at the start and the response body at the end)

## Fixing

Don't know exactly how this could be handled, as it could have been a conscious choice to make it like that. I think depending on the decision I'd be able to fix this issue, but I'll first let some cofounders discuss the problem here :)

**Comment by fargito** [comment]
Hello!

I think that currently you would normally have a typing error when returning a response such as 
```
{
  statusCode: 401,
  headers: {
    "x-custom-header" : "my custom header value"
  },
  body: JSON.stringify(responseBody)
};
```
in a lambda with its event generated with Swarmion. Do you have `additionalProperties: false` set on your output schema? However this seems like a valid use case, because only errors from the `http-errors` package are currently supported.

The import decision here is how we want to define error cases with serverless contracts. As I view it we have three options:

### 1. Require errors to be included in the contract output

This would mean your contract definition looks like:
```
const outputSchema = {
  type: 'object',
  oneOf: [
    {
      type: 'object',

      properties: {
        status: { enum: ['ACCEPTED', 'REJECTED'] },
        message: { type: 'string' },
      },
      required: ['status', 'message'],
      additionalProperties: false,
    },
    {
      type: 'object',
      properties: {
        statusCode: { enum: [401, 502] },
        body: { type: 'string' },
        headers: { type: 'object' },
      },
      required: ['statusCode', 'body'],
      additionalProperties: false,
    },
  ],
} as const;
```

- Pros: 
    - matches the Serverless docs
    - can be used to document the API in an OpenAPI schema
- Cons:
   - I becomes pretty heavy to define responses!
   - we need to add a check on whether the response is a "Serverless-like" or "Swarmion-like" when formatting the response, which could increase latency
   - what of errors thrown with the `http-errors` package?
   - what of errors thrown with other status codes?

### 2. Accept all reasonable error responses

This would mean any object that has type `Ouput<typeof contract>`:
```
type ApiGatewayProxyError = {
    statusCode: number;
    body: string; // we can't enforce schema type inference here
    headers?: Record<string, string>,
}
```

- Pros: 
    - matches the Serverless docs
- Cons:
   - this cannot benefit from Swarmion type safety and therefore is more error-prone
   - we need to add a check on whether the response is a "Serverless-like" or "Swarmion-like" when formatting the response, which could increase latency

### 3. Require http errors to be thrown via the `http-errors` package

This is currently the only option, but maybe we want to keep it that way.
- Pros: 
    - no changes
    - simpler contract definition
    - still good type safety
- Cons:
    - confusing compared to the Serverless docs

---

@adriencaccia @Sc0ra WDYT?

**Comment by Sc0ra** [comment]
I like the fact to add mutiple response format in the contract, mainly for the documentation side. We could change the definition format to allow it.

However, i would stick to Option 3 to raise error codes from your handler with Swarmion. This had a new abstraction layer and we need to add documentation for it, but it looks like the best interface to me, because the httpLambdaHandler was though to abstract all the http logic from the handler.

**Comment by GuillaumeLagrange** [comment]
Could we aim to provide two helpers ? One "all-included" and one where you could manually set a lot more things ?

**Comment by adriencaccia** [comment]
I agree with @Sc0ra. For now, let's document how to return errors "Swarmion-like".

Later, we can think how to add errors to contracts for documentation and typing purposes.

**Comment by fargito** [comment]
Closing this for now, we'll see in the future if this is needed
