### ISSUE TITLE
TS module error when trying to deploy

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#356]
Hello,

On `v0.14.0`, when trying to deploy the whole monorepo, I have the error:
```
    ✖  nx run backend-orchestrator:deploy
       > @swarmion/backend-orchestrator@0.14.0 deploy ........./swarmion/backend/orchestrator
       > serverless deploy
       
       Environment: linux, node 16.17.0, framework 3.25.0 (local), plugin 6.2.2, SDK 4.3.2
       Docs:        docs.serverless.com
       Support:     forum.serverless.com
       Bugs:        github.com/serverless/serverless/issues
       
       Error:
       Cannot load "serverless.ts": Initialization error: /home/fargito/Documents/theodo/swarmion/backend/orchestrator/serverless.ts:1
       import { listDeploymentsContract, onDeploymentRequestedContract, requestSyncDeploymentContract, } from '@swarmion/orchestrator-contracts';
       ^^^^^^
```
I believe the TS `"module"` setting is incorrect for Serverless services. It is set to `esnext` and should be `node16`.
However, I agree that `esnext` should be the value for frontend services.

I think we should set `"module": "node16"` in the root tsconfig and override it only in frontend packages in the examples.

@adriencaccia WDYT?

**Comment by adriencaccia** [comment]
Thank you for the issue!

Going further than what you pointed out, now all `serverless` cli commands will not work since they are using `ts-node` under the hood, which uses the `tsconfig.json` file.

Since this is an implementation detail of the `serverless` framework and how it uses `ts-node`, I would recommend to add it only in the `serverless` services. Like this:

```diff
{
  ...
  "ts-node": {
+   "compilerOptions": {
+     "module": "node16"
+   },
    "files": true
}
```

WDYT?
